spring.application.name=arquitectura-hexagonal

# SQL Server Configuration
spring.datasource.url=jdbc:sqlserver://localhost:1433;DatabaseName=Cibertec;encrypt=false;trustServerCertificate=false;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=sql

# JPA Configuration
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update

# GraphQL Configuration
spring.graphql.graphiql.enabled=true
